//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonopolyCash.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonopolyCash.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        internal static string aceptar {
            get {
                return ResourceManager.GetString("aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        internal static string acercaDe {
            get {
                return ResourceManager.GetString("acercaDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information about the app.
        /// </summary>
        internal static string acercaDe_detail {
            get {
                return ResourceManager.GetString("acercaDe_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update.
        /// </summary>
        internal static string actualizar {
            get {
                return ResourceManager.GetString("actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Special Thanks: Miguel Garcia Valero.
        /// </summary>
        internal static string agradecimientos {
            get {
                return ResourceManager.GetString("agradecimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Name.
        /// </summary>
        internal static string cambiar_nombre {
            get {
                return ResourceManager.GetString("cambiar_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Page where you can change names.
        /// </summary>
        internal static string cambiar_nombre_detail {
            get {
                return ResourceManager.GetString("cambiar_nombre_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change names.
        /// </summary>
        internal static string cambiar_nombres {
            get {
                return ResourceManager.GetString("cambiar_nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a amount.
        /// </summary>
        internal static string cantidad {
            get {
                return ResourceManager.GetString("cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credits:.
        /// </summary>
        internal static string creditos {
            get {
                return ResourceManager.GetString("creditos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Developer: Rodrigo Huerta Gañán.
        /// </summary>
        internal static string desarrollador {
            get {
                return ResourceManager.GetString("desarrollador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MonopolyCash is an app that allows you to know how much money has each player while you are playing Monopoly.
        /// </summary>
        internal static string explicacion {
            get {
                return ResourceManager.GetString("explicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        internal static string inicio {
            get {
                return ResourceManager.GetString("inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main Page.
        /// </summary>
        internal static string inicio_detail {
            get {
                return ResourceManager.GetString("inicio_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player.
        /// </summary>
        internal static string jugador {
            get {
                return ResourceManager.GetString("jugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Name.
        /// </summary>
        internal static string nuevo_nombre {
            get {
                return ResourceManager.GetString("nuevo_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of players.
        /// </summary>
        internal static string numero_de_jugadores {
            get {
                return ResourceManager.GetString("numero_de_jugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restart.
        /// </summary>
        internal static string reiniciar {
            get {
                return ResourceManager.GetString("reiniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transactions.
        /// </summary>
        internal static string transacciones {
            get {
                return ResourceManager.GetString("transacciones", resourceCulture);
            }
        }
    }
}
